var ntt = ntt || {};

ntt.tunes = [
  'American Boy',
  'Apologize',
  'Bad Romance',
  'Dilemma',
  'Firework',
  'Forget You',
  'Gold Digger',
  'Hero',
  'Hey Ya',
  'Hips Dont Lie',
  'I Dont Feel Like Dancing',
  'In For The Kill',
  'Independent Woman',
  'Is This The Way To Amarillo',
  'It Wasnt Me',
  'Love The Way You Lie',
  'Low',
  'Moves Like Jagger',
  'Poker Face',
  'Pure And Simple',
  'Sex On Fire',
  'Sexy And I Know It',
  'Single Ladies',
  'Someone Like You',
  'Use Somebody',
  'Viva La Vida',
  'When Love Takes Over',
  'Where Is The Love',
  'Whole Again',
  'Yeah'];
