var ntt = ntt || {};

ntt.poptunes = [
  'American Boy',
  'Apologize',
  'Bad Romance',
  'Dilemma',
  'Firework',
  'Forget You',
  'Gold Digger',
  'Hero',
  'Hey Ya',
  'Hips Dont Lie',
  'I Dont Feel Like Dancing',
  'In For The Kill',
  'Independent Woman',
  'Is This The Way To Amarillo',
  'It Wasnt Me',
  'Love The Way You Lie',
  'Low',
  'Moves Like Jagger',
  'Poker Face',
  'Pure And Simple',
  'Sex On Fire',
  'Sexy And I Know It',
  'Single Ladies',
  'Someone Like You',
  'Use Somebody',
  'Viva La Vida',
  'When Love Takes Over',
  'Where Is The Love',
  'Whole Again',
  'Yeah'];

ntt.rocktunes = [
  'All Right Now',
  'American Woman',
  'Barracuda',
  'Dont Fear The Reaper',
  'Dont Stop Believing',
  'Enter Sandman',
  'Fortunate Son',
  'LA Woman',
  'More Than A Feeling',
  'Rock And Roll All Nite',
  'Rocket Man',
  'Schools Out',
  'Smoke On The Water',
  'Space Oddity',
  'Sultans Of Swing',
  'Sunshine Of Your Love',
  'Sweet Child O Mine',
  'Sweet Emotion',
  'Sweet Home Alabama',
  'All Along The Watchtower',
  'Baba ORiley',
  'Bohemian Rhapsody',
  'Burning Down The House',
  'Free Fallin',
  'Hotel California',
  'La Grange',
  'Roxanne',
  'Slow Ride',
  'Stranglehold',
  'You Really Got Me'];

ntt.hiphoptunes = [
  '93 Til Infinity',
  '99 Problems',
  'Big Pimpin',
  'California Love',
  'CREAM',
  'Dear Mama',
  'Fight The Power',
  'G Thang',
  'I Know You Got Soul',
  'It Takes Two',
  'Juicy',
  'Me Myself And I',
  'Mind Playing Tricks On Me',
  'NY State Of Mind',
  'Ooh La La La',
  'Paid In Full',
  'Passin Me By',
  'Peter Piper',
  'Planet Rock',
  'Push It',
  'Rappers Delight',
  'Rebel Without A Pause',
  'Scenario',
  'Shook Ones',
  'Strictly Business',
  'Sucker MCs',
  'The Message',
  'They Reminisce Over You',
  'Today Was A Good Day',
  'Whats Golden'];

ntt.alltunes = (ntt.poptunes).concat(ntt.rocktunes, ntt.hiphoptunes);
